import { expect, test } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";

const evidence = process.env.E2E_EVIDENCE_DIR ?? ".local/evidence";
test.beforeAll(async () => { await mkdir(evidence, { recursive: true }); });

test("native construct, protect, revise, compare and restore survives reload", async ({ page }) => {
  test.setTimeout(180_000);
  await page.goto("/");
  await page.locator(".session-rail").getByRole("button", { name: "New session" }).click();
  await expect(page.getByRole("heading", { name: "Make something yours" })).toBeVisible();
  const direction = page.getByRole("textbox", { name: "Describe your arrangement" });
  await direction.fill("Build an evolving 64-bar ambient journey with a slow lead and spacious transitions");
  await page.getByRole("button", { name: "Create arrangement" }).click();
  await expect(page.getByRole("heading", { name: /ambient|journey|piece/i }).first()).toBeVisible({ timeout: 90_000 });
  await expect(page.getByText(/64 bars.*8 editable parts/)).toBeVisible({ timeout: 90_000 });
  const project = (await (await page.request.get("/api/v1/projects")).json() as { projects: Array<{ id: string; title: string }> }).projects[0]!;
  expect(project.title).not.toBe("Untitled listening room");
  const projectId = project.id;
  const currentNativeId = (await (await page.request.get(`/api/v1/projects/${projectId}/native`)).json() as { currentRevisionId: string }).currentRevisionId;
  const forbiddenSync = await page.request.post(`/api/v1/projects/${projectId}/native/synchronizations`, { headers: { "Idempotency-Key": crypto.randomUUID() }, data: { baseNativeRevisionId: currentNativeId, expectedNativeHeadId: currentNativeId } });
  expect(forbiddenSync.status()).toBe(409);
  await expect(page.getByText("This arrangement isn't playable yet.")).toBeVisible();
  await expect(page.getByRole("button", { name: "Play current version" })).toHaveCount(0);
  await page.getByLabel("Upload a WAV source").setInputFiles(resolve(".local/fixtures/owned-percussion.wav"));
  await expect(page.getByRole("dialog", { name: "Your sounds" })).toBeVisible();
  await page.getByRole("dialog", { name: "Your sounds" }).getByRole("button", { name: "Close" }).click();
  await expect(page.getByRole("dialog", { name: "Your sounds" })).toBeHidden();
  await page.locator(".workspace-side").getByRole("button", { name: "Play sound owned-percussion.wav" }).click();
  await expect(page.locator(".workspace-side").getByRole("slider", { name: "Seek through the source" })).toBeVisible();
  await page.getByRole("button", { name: "Playable audio" }).click();
  await expect(page.getByRole("slider", { name: "Seek through the source" })).toHaveCount(0);
  await page.getByRole("button", { name: "Arrange" }).click();
  await page.getByRole("button", { name: "Keep unchanged Slow lead for the next change" }).click();
  await expect(page.getByRole("button", { name: "Change Slow lead" })).toBeDisabled();
  const leadCard = page.locator(".native-part-card").filter({ has: page.getByRole("heading", { name: "Slow lead" }) });
  await leadCard.getByRole("button", { name: "Details" }).click();
  const detailDialog = page.getByRole("dialog", { name: "Slow lead" });
  await expect(detailDialog).toContainText("This is not an audio preview");
  await detailDialog.getByRole("button", { name: "Close" }).first().click();
  await expect(leadCard.getByRole("button", { name: "Details" })).toBeFocused();
  await page.getByRole("button", { name: "Change Soft pulse" }).click();
  await page.getByRole("button", { name: /Ascent.*Bars/i }).click();
  await expect(page.getByText(/In Ascent · change Soft pulse/)).toBeVisible();
  await direction.fill("Vary the rhythmic phrase in the later section while preserving the slow lead");
  const pending = "Vary the rhythmic phrase in the later section while preserving the slow lead";
  await page.getByRole("button", { name: "Playable audio" }).click();
  await page.getByRole("button", { name: "Arrange" }).click();
  await expect(direction).toHaveValue(pending);
  await expect(page.getByText(/In Ascent · change Soft pulse/)).toBeVisible();
  await expect(page.getByRole("button", { name: "Allow changes to Slow lead for the next change" })).toHaveAttribute("aria-pressed", "true");
  await page.reload();
  await expect(direction).toHaveValue(pending);
  await expect(page.getByText(/In Ascent · change Soft pulse/)).toBeVisible();
  await page.locator(".session-rail").getByRole("button", { name: "New session" }).click();
  await expect(page.getByRole("heading", { name: "Make something yours" })).toBeVisible();
  await expect(page.getByRole("textbox", { name: "Describe your arrangement" })).not.toHaveValue(pending);
  await page.locator(`.session-rail .rail-session[data-project-id="${projectId}"]`).click();
  await expect(direction).toHaveValue(pending);
  await expect(page.getByText(/In Ascent · change Soft pulse/)).toBeVisible();
  await page.getByRole("button", { name: "Shape the arrangement" }).click();
  await expect(page.getByText(/2 saved versions/)).toBeVisible({ timeout: 90_000 });
  await page.getByRole("button", { name: "Compare" }).click();
  const dialog = page.getByRole("dialog", { name: "Compare arrangements" });
  await expect(dialog).toBeVisible();
  await dialog.getByRole("radio", { name: "Version 1" }).click();
  await expect(dialog.getByText(/Allowed to change:.*Slow lead/)).toBeVisible();
  await dialog.getByRole("button", { name: "Restore this version" }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByText(/2 saved versions/)).toBeVisible();
  await expect(page.getByRole("button", { name: "Keep unchanged Slow lead for the next change" })).toHaveAttribute("aria-pressed", "false");
  await page.reload();
  await page.locator(`.session-rail .rail-session[data-project-id="${projectId}"]`).click();
  await expect(page.getByText(/64 bars.*8 editable parts/)).toBeVisible();
  await page.getByText("Explore detailed capabilities").click();
  await page.getByPlaceholder("Find instruments or effects").fill("beatbox8");
  await expect(page.getByText("beatbox8", { exact: true }).first()).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `${evidence}/native-desktop.png`, fullPage: true });
});

test("native phone layout preserves direction focus and compare dialog return", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  await page.locator(".session-rail").getByRole("button", { name: "New session" }).click();
  await page.getByRole("textbox", { name: "Describe your arrangement" }).fill("A quiet 32-bar instrumental sketch for mobile review");
  await page.getByRole("button", { name: "Create arrangement" }).click();
  await expect(page.getByText(/1 saved version/)).toBeVisible({ timeout: 90_000 });
  await page.setViewportSize({ width: 390, height: 844 });
  const direction = page.getByRole("textbox", { name: "Describe your arrangement" });
  await direction.focus();
  const box = await direction.boundingBox();
  expect(box).not.toBeNull();
  expect((box?.x ?? 1_000) + (box?.width ?? 1_000)).toBeLessThanOrEqual(390);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.getByRole("button", { name: "Compare" }).click();
  const dialog = page.getByRole("dialog", { name: "Compare arrangements" });
  await expect(dialog).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "Compare" })).toBeFocused();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `${evidence}/native-mobile.png`, fullPage: true });
});

test("tablet progressively discloses a large arrangement without horizontal overflow", async ({ page }) => {
  await page.goto("/");
  await page.locator(".session-rail").getByRole("button", { name: "New session" }).click();
  await page.getByRole("textbox", { name: "Describe your arrangement" }).fill("An evolving arrangement with many interacting parts");
  await page.getByRole("button", { name: "Create arrangement" }).click();
  await expect(page.getByText(/1 saved version/)).toBeVisible({ timeout: 90_000 });
  await page.route("**/api/v1/projects/*/native", async (route) => {
    const response = await route.fetch();
    const snapshot = await response.json() as { current: { document: { parts: Array<{ id: string; name: string }> } } | null };
    if (snapshot.current) {
      const parts = snapshot.current.document.parts;
      snapshot.current.document.parts = [...parts, ...parts.map((part) => ({ ...part, id: `${part.id}-second`, name: `${part.name} second voice` }))];
    }
    await route.fulfill({ response, json: snapshot });
  });
  await page.setViewportSize({ width: 820, height: 1180 });
  await page.reload();
  await expect(page.getByRole("group", { name: "Filter parts by role" })).toBeVisible();
  await expect(page.locator(".native-part-card")).toHaveCount(8);
  await page.getByRole("button", { name: /Show more parts/ }).click();
  await expect(page.locator(".native-part-card")).toHaveCount(16);
  await page.getByRole("group", { name: "Filter parts by role" }).getByRole("button", { name: /percussion/i }).click();
  await expect(page.locator(".native-part-card")).toHaveCount(4);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(820);
  await page.screenshot({ path: `${evidence}/native-tablet-large.png`, fullPage: true });
});
