import { decodeWav, measureDecodedWav } from "../audio/wav.js";
import { canonicalHash } from "../domain/hash.js";

export interface NativeSourceSegment { startSeconds: number; endSeconds: number; rms: number; nonSilentRatio: number }
export interface NativeSourceProfile { durationSeconds: number; peak: number; rms: number; nonSilentRatio: number; segments: NativeSourceSegment[]; leadingSilenceSeconds: number; suggestedSlices: Array<{ startSeconds: number; endSeconds: number; reason: string }>; limitations: string }

export function profileOwnedSourceWav(bytes: Buffer): NativeSourceProfile {
  const audio = decodeWav(bytes);
  const whole = measureDecodedWav(audio);
  const segments: NativeSourceSegment[] = [];
  const count = Math.min(8, Math.max(1, Math.ceil(audio.durationSeconds / 2)));
  for (let index = 0; index < count; index++) {
    const first = Math.floor(index * audio.frames / count);
    const last = Math.floor((index + 1) * audio.frames / count);
    const slice = { ...audio, frames: last - first, durationSeconds: (last - first) / audio.sampleRate, channels: audio.channels.map((channel) => channel.subarray(first, last)) };
    const measured = measureDecodedWav(slice);
    segments.push({ startSeconds: first / audio.sampleRate, endSeconds: last / audio.sampleRate, rms: Number(measured.rms.toFixed(5)), nonSilentRatio: Number(measured.nonSilentRatio.toFixed(3)) });
  }
  const windowFrames = Math.max(1, Math.floor(audio.sampleRate / 8));
  const windows: Array<{ start: number; end: number; rms: number }> = [];
  for (let first = 0; first < audio.frames; first += windowFrames) {
    const last = Math.min(audio.frames, first + windowFrames);
    let energy = 0;
    for (const channel of audio.channels) for (let frame = first; frame < last; frame++) energy += channel[frame]! ** 2;
    windows.push({ start: first / audio.sampleRate, end: last / audio.sampleRate, rms: Math.sqrt(energy / ((last - first) * audio.channels.length)) });
  }
  const activityThreshold = Math.max(0.008, whole.rms * 0.35);
  const firstActive = windows.find((window) => window.rms >= activityThreshold);
  const leadingSilenceSeconds = firstActive?.start ?? audio.durationSeconds;
  const ranked = windows.map((window, index) => ({ ...window, score: window.rms - (windows[index - 1]?.rms ?? 0) * 0.4 })).filter((window) => window.rms >= activityThreshold).sort((a, b) => b.score - a.score);
  const suggestedSlices: NativeSourceProfile["suggestedSlices"] = [];
  for (const window of ranked) {
    const startSeconds = Number(window.start.toFixed(3));
    if (suggestedSlices.some((slice) => Math.abs(slice.startSeconds - startSeconds) < 0.35)) continue;
    suggestedSlices.push({ startSeconds, endSeconds: Number(Math.min(audio.durationSeconds, window.end + 0.25).toFixed(3)), reason: "Measured activity/onset candidate; inspect before placement" });
    if (suggestedSlices.length === 6) break;
  }
  suggestedSlices.sort((a, b) => a.startSeconds - b.startSeconds);
  return { durationSeconds: audio.durationSeconds, peak: Number(whole.peak.toFixed(5)), rms: Number(whole.rms.toFixed(5)), nonSilentRatio: Number(whole.nonSilentRatio.toFixed(3)), segments, leadingSilenceSeconds: Number(leadingSilenceSeconds.toFixed(3)), suggestedSlices, limitations: "Energy-based candidates only; tempo, pitch, instrument identity and rights are not inferred." };
}

// Versioned, inspectable parameter hypotheses. These are executable SDK
// settings, not Audiotool presets or evidence that anyone has heard them.
export const NATIVE_RECIPE_VERSION = "local-palette-v3";
export const nativePresetRecipes = [
  { id: "soft-glass", styles: ["ambient", "lo-fi", "cinematic"], name: "Soft glass", character: "Rounded sustained keys with a long attack", role: "harmony", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { "operatorA.gain": 0.5, "operatorB.gain": 0.16, "operatorB.modulationFactorA": 0.18, "filter.cutoffFrequencyHz": 1700, "envelopeMain.attackTimeNormalized": 0.34, "envelopeMain.sustainFactor": 0.72 } }, effects: [{ type: "stompboxReverb", parameters: { roomSizeFactor: 0.58, mix: 0.23 } }] },
  { id: "low-hollow", styles: ["ambient", "lo-fi", "downtempo"], name: "Low hollow", character: "Restrained low register with a soft edge", role: "bass", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "pulverisateur", parameters: { "filter.cutoffFrequencyHz": 640, "filter.resonance": 0.38 } }, effects: [{ type: "stompboxCompressor", parameters: { thresholdDb: -12, ratio: 0.4 } }] },
  { id: "short-echo", styles: ["pop", "synth", "downtempo"], name: "Short echo", character: "Dry phrase with a restrained rhythmic reply", role: "lead", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { "filter.cutoffFrequencyHz": 3200, "envelopeMain.sustainFactor": 0.42 } }, effects: [{ type: "stompboxDelay", parameters: { feedbackFactor: 0.22, mix: 0.18, stepCount: 2 } }] },
  { id: "rubber-pulse", styles: ["disco", "funk", "synth"], name: "Rubber pulse", character: "Short syncopated bass with upper harmonics", role: "bass", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { "operatorA.gain": 0.65, "operatorB.gain": 0.2, "operatorB.modulationFactorA": 0.32, "filter.cutoffFrequencyHz": 1100, "envelopeMain.decayTimeNormalized": 0.19, "envelopeMain.sustainFactor": 0.32 } }, effects: [{ type: "stompboxCompressor", parameters: { thresholdDb: -16, ratio: 0.45 } }] },
  { id: "bright-stabs", styles: ["disco", "house", "funk"], name: "Bright stabs", character: "Brief chord accents that can open during a build", role: "harmony", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { "operatorA.gain": 0.55, "operatorB.gain": 0.24, "operatorB.modulationFactorA": 0.25, "filter.cutoffFrequencyHz": 3900, "envelopeMain.decayTimeNormalized": 0.17, "envelopeMain.sustainFactor": 0.27 } }, effects: [{ type: "stompboxChorus", parameters: { delayTimeMs: 28, lfoFrequencyHz: 0.65, lfoModulationDepth: 0.23 } }] },
  { id: "airline", styles: ["synth", "pop", "ambient"], name: "Airline", character: "A higher sustained counterline with room to breathe", role: "lead", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { "operatorA.gain": 0.51, "operatorB.gain": 0.11, "filter.cutoffFrequencyHz": 4800, "envelopeMain.attackTimeNormalized": 0.11, "envelopeMain.sustainFactor": 0.68 } }, effects: [{ type: "stompboxReverb", parameters: { roomSizeFactor: 0.46, mix: 0.17 } }] },
  { id: "dry-step-kit", styles: ["minimal", "synth"], name: "Dry step kit", character: "Four fixed drum voices for a simple, editable pulse; steps are on/off", role: "drums", provenance: "Pocket Producer original parameter recipe; not a Gakki kit and unheard", device: { type: "beatbox8", parameters: { "bassdrum.gain": 0.82, "bassdrum.decay": 0.28, "snaredrum.gain": 0.66, "snaredrum.snappy": 0.57, "openHihat.decay": 0.24 } }, effects: [] },
  { id: "lofi-keys", styles: ["lo-fi", "chillhop", "neo-soul", "jazz"], name: "Lo-fi keys", character: "Soft electric-piano chords with gentle wobble and warm saturation", role: "harmony", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { "operatorA.gain": 0.6, "operatorB.gain": 0.28, "operatorB.modulationFactorA": 0.3, "filter.cutoffFrequencyHz": 2400, velocityFactor: 0.7, "envelopeMain.attackTimeNormalized": 0.04, "envelopeMain.decayTimeNormalized": 0.42, "envelopeMain.sustainFactor": 0.38, "envelopeMain.releaseTimeNormalized": 0.36 } }, effects: [{ type: "stompboxChorus", parameters: { delayTimeMs: 26, feedbackFactor: 0.1, lfoFrequencyHz: 0.7, lfoModulationDepth: 0.32, spreadFactor: 0.6 } }, { type: "stompboxTube", parameters: { drive: 1.6, tone: -3, postGain: 0.85 } }, { type: "stompboxReverb", parameters: { roomSizeFactor: 0.42, preDelayTimeMs: 18, feedbackFactor: 0.4, mix: 0.18 } }] },
  { id: "warm-pad", styles: ["ambient", "cinematic", "lo-fi", "chill"], name: "Warm pad", character: "Wide, slowly blooming sustained chords", role: "harmony", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { unisonoCount: 3, unisonoDetuneSemitones: 0.12, unisonoStereoSpreadFactor: 0.6, "operatorA.gain": 0.55, "operatorB.gain": 0.12, "operatorB.modulationFactorA": 0.1, "filter.cutoffFrequencyHz": 1500, "envelopeMain.attackTimeNormalized": 0.58, "envelopeMain.sustainFactor": 0.86, "envelopeMain.releaseTimeNormalized": 0.62 } }, effects: [{ type: "stompboxChorus", parameters: { delayTimeMs: 34, lfoFrequencyHz: 0.25, lfoModulationDepth: 0.4, spreadFactor: 0.8 } }, { type: "stompboxReverb", parameters: { roomSizeFactor: 0.72, preDelayTimeMs: 40, feedbackFactor: 0.6, mix: 0.32 } }] },
  { id: "glass-bell", styles: ["ambient", "lullaby", "cinematic", "lo-fi"], name: "Glass bell", character: "Clear struck bell tones with a soft echo", role: "lead", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { "operatorA.gain": 0.5, "operatorB.gain": 0.3, "operatorB.modulationFactorA": 0.46, "filter.cutoffFrequencyHz": 6000, "envelopeMain.attackTimeNormalized": 0.01, "envelopeMain.decayTimeNormalized": 0.55, "envelopeMain.sustainFactor": 0.08, "envelopeMain.releaseTimeNormalized": 0.5 } }, effects: [{ type: "stompboxDelay", parameters: { feedbackFactor: 0.32, mix: 0.2, stepCount: 3, stepLengthIndex: 2 } }, { type: "stompboxReverb", parameters: { roomSizeFactor: 0.6, mix: 0.24 } }] },
  { id: "sub-round", styles: ["house", "techno", "hip-hop", "pop", "ambient"], name: "Round sub", character: "Deep, steady low end that leaves room above", role: "bass", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "pulverisateur", parameters: { "filter.cutoffFrequencyHz": 380, "filter.resonance": 0.12, "audio.drive": 0.08 } }, effects: [{ type: "stompboxCompressor", parameters: { thresholdDb: -14, ratio: 0.45, attackMs: 12, releaseMs: 160, makeupGainDb: 3 } }] },
  { id: "dusty-bass", styles: ["lo-fi", "hip-hop", "boom-bap", "soul"], name: "Dusty bass", character: "Rounded, slightly saturated bass with a soft knock", role: "bass", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "pulverisateur", parameters: { "filter.cutoffFrequencyHz": 820, "filter.resonance": 0.28, "audio.drive": 0.3 } }, effects: [{ type: "stompboxTube", parameters: { drive: 2.4, tone: -2, postGain: 0.8 } }, { type: "stompboxCompressor", parameters: { thresholdDb: -16, ratio: 0.5, attackMs: 8, releaseMs: 140 } }] },
  { id: "pluck-arp", styles: ["synthwave", "house", "pop", "ambient"], name: "Pluck arp", character: "Short bright plucks for arpeggios and rhythmic chords", role: "texture", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { "operatorA.gain": 0.55, "operatorB.gain": 0.22, "operatorB.modulationFactorA": 0.34, "filter.cutoffFrequencyHz": 3400, "envelopeMain.attackTimeNormalized": 0, "envelopeMain.decayTimeNormalized": 0.14, "envelopeMain.sustainFactor": 0.04, "envelopeMain.releaseTimeNormalized": 0.2 } }, effects: [{ type: "stompboxDelay", parameters: { feedbackFactor: 0.34, mix: 0.22, stepCount: 3, stepLengthIndex: 1 } }, { type: "stompboxReverb", parameters: { roomSizeFactor: 0.4, mix: 0.14 } }] },
  { id: "string-swell", styles: ["cinematic", "orchestral", "ambient"], name: "String swell", character: "Slow ensemble-like swells for long chords", role: "harmony", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { unisonoCount: 4, unisonoDetuneSemitones: 0.18, unisonoStereoSpreadFactor: 0.8, "operatorA.gain": 0.5, "operatorB.gain": 0.18, "operatorB.modulationFactorA": 0.14, "filter.cutoffFrequencyHz": 2600, "envelopeMain.attackTimeNormalized": 0.72, "envelopeMain.sustainFactor": 0.9, "envelopeMain.releaseTimeNormalized": 0.7 } }, effects: [{ type: "autoFilter", parameters: { cutoffFrequencyHz: 2800, mix: 0.35, filterModulationDepth: 0.2 } }, { type: "stompboxReverb", parameters: { roomSizeFactor: 0.8, preDelayTimeMs: 50, mix: 0.34 } }] },
  { id: "soft-lead", styles: ["pop", "synthwave", "lo-fi", "house"], name: "Soft lead", character: "A singing mono-style lead with a little grit and echo", role: "lead", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { glideMs: 60, "operatorA.gain": 0.58, "operatorB.gain": 0.16, "operatorB.modulationFactorA": 0.2, "filter.cutoffFrequencyHz": 3600, "envelopeMain.attackTimeNormalized": 0.06, "envelopeMain.sustainFactor": 0.66, "envelopeMain.releaseTimeNormalized": 0.3 } }, effects: [{ type: "stompboxTube", parameters: { drive: 1.2, tone: 1, postGain: 0.9 } }, { type: "stompboxDelay", parameters: { feedbackFactor: 0.26, mix: 0.16, stepCount: 3, stepLengthIndex: 2 } }] },
  { id: "house-stab", styles: ["house", "disco", "garage"], name: "House stab", character: "Punchy short chord stabs for off-beat grooves", role: "harmony", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { "operatorA.gain": 0.6, "operatorB.gain": 0.3, "operatorB.modulationFactorA": 0.38, "filter.cutoffFrequencyHz": 3000, "envelopeMain.attackTimeNormalized": 0, "envelopeMain.decayTimeNormalized": 0.2, "envelopeMain.sustainFactor": 0.15, "envelopeMain.releaseTimeNormalized": 0.18 } }, effects: [{ type: "stompboxChorus", parameters: { delayTimeMs: 22, lfoFrequencyHz: 0.9, lfoModulationDepth: 0.25 } }, { type: "stompboxReverb", parameters: { roomSizeFactor: 0.35, mix: 0.14 } }] },
  { id: "drifting-haze", styles: ["ambient", "lo-fi", "cinematic"], name: "Drifting haze", character: "A soft moving background texture for long held notes", role: "texture", provenance: "Pocket Producer original parameter recipe; unheard", device: { type: "heisenberg", parameters: { "operatorA.gain": 0.42, "operatorB.gain": 0.2, "operatorB.modulationFactorA": 0.22, "filter.cutoffFrequencyHz": 1200, "envelopeMain.attackTimeNormalized": 0.45, "envelopeMain.sustainFactor": 0.75, "envelopeMain.releaseTimeNormalized": 0.55 } }, effects: [{ type: "autoFilter", parameters: { cutoffFrequencyHz: 1400, mix: 0.6, filterModulationDepth: 0.45 } }, { type: "stompboxReverb", parameters: { roomSizeFactor: 0.75, preDelayTimeMs: 60, mix: 0.4 } }] },
  { id: "punchy-step-kit", styles: ["house", "techno", "electro"], name: "Punchy step kit", character: "Tighter Beatbox8 voices for straight four-on-the-floor patterns; steps are on/off", role: "drums", provenance: "Pocket Producer original parameter recipe; not a Gakki kit and unheard", device: { type: "beatbox8", parameters: { gain: 0.85, "bassdrum.tone": 0.45, "bassdrum.decay": 0.42, "snaredrum.tone": 0.5, "snaredrum.snappy": 0.68, "openHihat.decay": 0.32 } }, effects: [{ type: "stompboxCompressor", parameters: { thresholdDb: -12, ratio: 0.5, attackMs: 6, releaseMs: 120 } }] }
] as const;

const recipeGuidance: Record<(typeof nativePresetRecipes)[number]["id"], { register: string; articulation: string; usefulMotion: string; failureMode: string }> = {
  "soft-glass": { register: "Middle register, roughly C4–C6", articulation: "Long notes with gaps; avoid stacking every beat", usefulMotion: "Bring the filter forward gradually only after a quiet opening", failureMode: "A long attack can blur fast chord changes" },
  "low-hollow": { register: "Low register, roughly C2–C4", articulation: "Short bass responses and held roots", usefulMotion: "Modest cutoff movement rather than a full-range sweep", failureMode: "Low cutoff can hide pitch definition" },
  "short-echo": { register: "Middle to upper lead register", articulation: "Short calls with deliberate rests", usefulMotion: "Increase echo send for a phrase ending", failureMode: "Repeated replies may crowd the next downbeat" },
  "rubber-pulse": { register: "Bass register, roughly C2–C4", articulation: "Syncopated notes with varied lengths", usefulMotion: "Open the filter on a later return", failureMode: "Very low notes or long sustains can muddy the groove" },
  "bright-stabs": { register: "Middle chord register", articulation: "Brief offbeat voicings with unplayed beats", usefulMotion: "A bounded filter rise over several phrases", failureMode: "Dense voicings plus chorus can mask the lead" },
  airline: { register: "Upper melodic register", articulation: "Spaced call and response", usefulMotion: "Bring in the shared reverb on selected phrases", failureMode: "Sustained high notes can dominate a sparse texture" },
  "dry-step-kit": { register: "Four mapped drum voices only", articulation: "On/off kick, snare and hats; do not claim velocity expression", usefulMotion: "Add/remove steps or a brief gap before an arrival", failureMode: "This is not a resolved Gakki drum kit or humanized performance" },
  "lofi-keys": { register: "Chords around C3–C5; voice 4 notes with 7ths or 9ths", articulation: "Comped or held chords; let notes overlap a little", usefulMotion: "Open the filter slightly for a later section; swing comping lightly", failureMode: "Low dense voicings get muddy under the saturation" },
  "warm-pad": { register: "Middle register, roughly C3–C5", articulation: "Long held chords that change with the harmony", usefulMotion: "Raise the filter or the reverb send across a build", failureMode: "The slow attack blurs quick chord changes" },
  "glass-bell": { register: "Upper register, roughly C5–C7", articulation: "Sparse single notes with space for the echo", usefulMotion: "Thin out or add echo toward an ending", failureMode: "Dense phrases turn the echo into clutter" },
  "sub-round": { register: "Low register, roughly E1–E3", articulation: "Roots and simple rhythms that lock with the kick", usefulMotion: "Hold back in an intro, enter at the first arrival", failureMode: "Fast lines above C3 lose the sub weight" },
  "dusty-bass": { register: "Bass register, roughly E1–C3", articulation: "Rounded notes with a little space between them", usefulMotion: "Add a pickup note before a section change", failureMode: "Drive plus long notes can smear the low end" },
  "pluck-arp": { register: "Middle to upper register", articulation: "Arpeggios or short rhythmic chords", usefulMotion: "Raise the echo mix or the cutoff in a build", failureMode: "Constant 16ths with echo can blur the groove" },
  "string-swell": { register: "Wide chords from about C3 upward", articulation: "Slow swells on chord changes", usefulMotion: "Let the swells arrive with the section changes", failureMode: "Too slow for short chords; keep changes at a bar or longer" },
  "soft-lead": { register: "Melodic register, roughly C4–C6", articulation: "Legato phrases with rests between them", usefulMotion: "Raise the echo mix at phrase ends", failureMode: "Continuous playing leaves no room for other parts" },
  "house-stab": { register: "Middle chord register", articulation: "Short off-beat chord hits", usefulMotion: "Open the filter over a build; drop out before a return", failureMode: "Stabs on every 8th crowd the hats" },
  "drifting-haze": { register: "Low-middle to middle register", articulation: "Long held notes or soft clusters", usefulMotion: "Let it fade in under a section and out at the end", failureMode: "Too loud, it washes out the melody" },
  "punchy-step-kit": { register: "Four mapped drum voices only", articulation: "On/off steps at one fixed velocity; vary density, not dynamics", usefulMotion: "Change the pattern between sections; drop the kick for a break", failureMode: "Still fixed velocity and straight timing; a Gakki kit is better for swing" }
};

function recipeEvidence(recipe: (typeof nativePresetRecipes)[number]) {
  return { version: NATIVE_RECIPE_VERSION, configurationHash: canonicalHash({ version: NATIVE_RECIPE_VERSION, device: recipe.device, effects: recipe.effects }), usageTerms: "Original Pocket Producer parameter settings; Audiotool device/use terms still apply", auditionStatus: "unheard" as const, guidance: recipeGuidance[recipe.id] };
}

export function readNativeRecipe(id: string) {
  const recipe = nativePresetRecipes.find((item) => item.id === id);
  if (!recipe) throw new Error("Unknown local sound recipe; search resources first");
  return { ...recipe, ...recipeEvidence(recipe), verified: "canonical-to-offline-Nexus mapping only", heard: false, applyWith: "Name it as a scene part's recipe, or use applyRecipe in a sound or batch edit; it sets the device and adds the effect chain. Adapt to the brief and inspect the mapped result" };
}

export function searchNativeResources(query: string, sources: Array<{ assetId: string; name?: string; assetHash: string; durationSeconds: number; rights: string; profile?: NativeSourceProfile }>) {
  const normalized = query.trim().toLowerCase();
  const terms = [...new Set(normalized.match(/[a-z0-9]+/g) ?? [])].filter((term) => !["a", "the", "for", "with", "and", "sound", "sounds", "synth"].includes(term));
  const score = (text: string) => { const haystack = text.toLowerCase(); return (normalized && haystack.includes(normalized) ? 10 : 0) + terms.filter((term) => haystack.includes(term)).length; };
  const recipes = nativePresetRecipes.map((value) => ({ value, score: score(`${value.name} ${value.id} ${value.character} ${value.role} ${value.device.type} ${value.styles.join(" ")}`) })).filter((item) => !terms.length || item.score > 0).sort((a, b) => b.score - a.score || a.value.id.localeCompare(b.value.id)).slice(0, 6);
  return {
    ownedSamples: sources.filter((value) => !normalized || `${value.name ?? ""} ${value.assetId}`.toLowerCase().includes(normalized)).slice(0, 16).map((value) => ({ ...value, provenance: "selected owned source", state: "local-ready/remote-unverified" as const })),
    presetRecipes: recipes.map(({ value }) => ({ ...value, ...recipeEvidence(value), heard: false })),
    guidance: recipes.length ? "Choose one relevant recipe, adapt its mapped settings and construct. Recipes are not heard evidence." : "No matching local recipe. Try bass, harmony, lead or drums; built-in devices remain available.",
    remoteLibrary: "not queried; an Audiotool catalogue result is not an owned or selected source"
  };
}
