import { memo, useEffect, useMemo, useRef, useState } from "react"
import { MotionConfig, motion, useReducedMotion } from "motion/react"
import { ArrowLeft, ArrowRight, Focus, Layers3 } from "lucide-react"
import type { NativeDocument } from "../../lib/api"
import { Button } from "../../components/ui/button"
import { compareScoreSection, materializedSectionNotes, motifFamily, projectScoreOverview, sectionClips, ticksPerBar } from "./score"

const roleNames: Record<string, string> = { percussion: "Drums", bass: "Bass", melody: "Melody", harmony: "Harmony", texture: "Atmosphere", lead: "Lead", fx: "Accents", source: "Your sounds" }
const familyTone = (value: string) => Array.from(value).reduce((sum, char) => sum + char.charCodeAt(0), 0) % 4
const pitchName = (pitch: number) => `${["C", "C♯", "D", "D♯", "E", "F", "F♯", "G", "G♯", "A", "A♯", "B"][pitch % 12]}${Math.floor(pitch / 12) - 1}`
const barLabel = (tick: number, width: number) => `${Math.floor(tick / width) + 1}${tick % width ? ` + ${Number((tick % width / 960).toFixed(2))} beats` : ""}`

interface Props { document: NativeDocument; identity: string; selectedSectionId: string | null; onSelectSection(id: string | null): void; selectedPartId: string | null; onInspectPart(id: string): void; draft?: boolean; comparisonBefore?: NativeDocument; animateConfirmed?: boolean; confirmedStepCount?: number }

export const NativeScore = memo(function NativeScore({ document, identity, selectedSectionId, onSelectSection, selectedPartId, onInspectPart, draft = false, comparisonBefore, animateConfirmed = false, confirmedStepCount }: Props) {
  const overview = useMemo(() => projectScoreOverview(document), [document])
  const beforeOverview = useMemo(() => comparisonBefore ? projectScoreOverview(comparisonBefore) : null, [comparisonBefore])
  const reduced = useReducedMotion()
  const previous = useRef<{ identity: string; overview: typeof overview; stepCount?: number } | null>(null)
  const prior = previous.current
  const changed = animateConfirmed && prior && prior.identity !== identity ? overview.lanes.flatMap((lane) => lane.density.map((count, bar) => ({ partId: lane.partId, name: lane.name, bar, before: prior.overview.lanes.find((item) => item.partId === lane.partId)?.density[bar] ?? 0, after: count }))).filter((item) => item.before !== item.after) : []
  const animateChanges = Boolean(!reduced && prior && prior.identity !== identity && changed.length <= 120)
  const activity = changed?.length ? `${confirmedStepCount && prior?.stepCount && confirmedStepCount - prior.stepCount > 1 ? "Several confirmed changes arrived together. " : "Confirmed change: "}${[...new Set(changed.slice(0, 4).map((item) => `${item.name} ${item.after > item.before ? "gained" : "lost"} note starts near bar ${item.bar + 1}`))].join("; ")}${changed.length > 4 ? "; more changes in the score" : ""}.` : null
  useEffect(() => { previous.current = { identity, overview, stepCount: confirmedStepCount } }, [identity, overview, confirmedStepCount])
  const section = document.sections.find((item) => item.id === selectedSectionId) ?? null
  const sectionChanges = useMemo(() => comparisonBefore && section ? compareScoreSection(comparisonBefore, document, section.id) : null, [comparisonBefore, document, section])
  const [detailStart, setDetailStart] = useState<number | null>(null)
  const [highlightFamily, setHighlightFamily] = useState<string | null>(null)
  const windowStartBar = section ? Math.min(Math.max(detailStart ?? section.startBar, section.startBar), Math.max(section.startBar, section.endBar - 1)) : 0
  const windowEndBar = section ? Math.min(section.endBar, windowStartBar + 8) : 0
  const width = ticksPerBar(document)
  const windowStart = windowStartBar * width, windowEnd = windowEndBar * width
  const selectedPart = document.parts.find((part) => part.id === selectedPartId) ?? null
  const activeFamilies = useMemo(() => [...new Set(document.motifs.map((motif) => motifFamily(document, motif.id)).filter((value): value is string => Boolean(value)))], [document])
  const familyName = (family: string) => document.motifs.find((motif) => motif.id === family)?.name ?? document.motifs.find((motif) => motif.familyId === family)?.name ?? family
  return <MotionConfig reducedMotion="user">
    <div className={`living-score ${draft ? "is-draft" : ""}`} data-score-identity={identity}>
      <div className="score-legend"><span><i className="legend-density" /> Note starts per bar</span><span><i className="legend-motif" /> Repeated phrase</span><span><i className="legend-clip" /> Sound clip</span><span><i className="legend-focus" /> Focused section</span></div>
      <div className="score-scroll" tabIndex={0} role="region" aria-label={`${draft ? "Confirmed draft" : "Saved"} arrangement overview; scroll horizontally for all bars`}>
        <div className="score-canvas">
          <div className="score-heading-row"><span className="score-part-label">Parts</span><div className="score-section-track" role="group" aria-label="Choose a section">{document.sections.map((item, index) => <button key={item.id} type="button" className="score-section-choice" style={{ flexGrow: item.endBar - item.startBar }} aria-pressed={selectedSectionId === item.id} onClick={() => { setDetailStart(null); onSelectSection(selectedSectionId === item.id ? null : item.id) }}><small>{String(index + 1).padStart(2, "0")} · bars {item.startBar + 1}–{item.endBar}</small><strong>{item.name}</strong></button>)}</div></div>
          {overview.lanes.map((lane) => <div className="score-lane" key={lane.partId}>
            <button type="button" className="score-part-label" onClick={() => onInspectPart(lane.partId)} aria-label={`Inspect ${lane.name}, ${roleNames[lane.role] ?? lane.role}, ${lane.totalNoteOnsets} note starts and ${lane.totalClips} clips`}><small>{roleNames[lane.role] ?? lane.role}</small><strong>{lane.name}</strong></button>
            <svg className="score-lane-svg" viewBox="0 0 1000 48" preserveAspectRatio="none" role="img" aria-label={`${lane.name}: ${lane.totalNoteOnsets} note starts across ${document.bars} bars; ${lane.blocks.length} phrase or clip placements`}>
              {document.sections.map((item) => <rect key={item.id} x={item.startBar / document.bars * 1000} y="0" width={(item.endBar - item.startBar) / document.bars * 1000} height="48" className={selectedSectionId === item.id ? "score-section-active" : "score-section-area"} />)}
              {lane.density.map((count, bar) => { const previousCount = beforeOverview?.lanes.find((item) => item.partId === lane.partId)?.density[bar] ?? 0; const height = Math.min(26, 5 + Math.log2(count + 1) * 5); return <g key={bar}>{previousCount > count ? <rect x={(bar + 0.12) / document.bars * 1000} y={40 - Math.min(26, 5 + Math.log2(previousCount + 1) * 5)} width={Math.max(2, 0.76 / document.bars * 1000)} height={Math.min(26, 5 + Math.log2(previousCount + 1) * 5)} className="score-density-removed"><title>Bar {bar + 1}: {previousCount - count} fewer note starts than Before</title></rect> : null}{count ? <motion.rect key={`${bar}:${count}`} x={(bar + 0.12) / document.bars * 1000} y={40 - height} width={Math.max(2, 0.76 / document.bars * 1000)} height={height} className={`score-density role-${lane.role} ${beforeOverview && previousCount < count ? "score-density-added" : ""}`} initial={animateChanges && changed.some((item) => item.partId === lane.partId && item.bar === bar) ? { opacity: 0.3 } : false} animate={{ opacity: 1 }} transition={{ duration: 0.32 }}><title>Bar {bar + 1}: {count} note {count === 1 ? "start" : "starts"}{beforeOverview ? `, ${count - previousCount >= 0 ? "+" : ""}${count - previousCount} from Before` : ""}</title></motion.rect> : null}</g> })}
              {lane.blocks.slice(0, 120).map((block, index) => <rect key={block.key} x={block.startTick / (document.bars * width) * 1000} y={block.kind === "motif" ? 4 + index % 2 * 5 : 3} width={Math.max(2, (block.endTick - block.startTick) / (document.bars * width) * 1000)} height={block.kind === "motif" ? 7 : 12} rx="3" className={`score-block ${block.kind} ${block.familyId ? `family-${familyTone(block.familyId)}` : ""} ${highlightFamily && block.familyId !== highlightFamily ? "is-muted" : ""}`}><title>{block.label}, bars {barLabel(block.startTick, width)}–{barLabel(block.endTick, width)}{block.derivedFromMotifId ? "; related variation" : ""}</title></rect>)}
            </svg>
          </div>)}
        </div>
      </div>
      <p className="score-caption">{overview.noteOnsets.toLocaleString()}{overview.truncated ? "+" : ""} note starts mapped from saved notes and phrase placements · {document.parts.length} parts. Height counts onsets, not loudness. {overview.lanes.some((lane) => lane.blocks.length > 120) ? "Some repeated placements are summarized at this scale." : ""}</p>
      {activity ? <p className="score-activity" role="status">{activity}</p> : null}
      {activeFamilies.length ? <div className="score-themes" role="group" aria-label="Highlight recurring phrases"><span>Follow a phrase</span>{activeFamilies.slice(0, 8).map((family) => <Button key={family} variant={highlightFamily === family ? "default" : "outline"} size="sm" aria-pressed={highlightFamily === family} onClick={() => setHighlightFamily(highlightFamily === family ? null : family)}>{familyName(family)}</Button>)}{activeFamilies.length > 8 ? <span>+{activeFamilies.length - 8} more in part details</span> : null}</div> : null}
      {section ? <div className="score-detail" aria-label={`${section.name} details`}>
        <div className="score-detail-heading"><div><small>FOCUS · BARS {section.startBar + 1}–{section.endBar}</small><h3>{section.name}</h3><p>{section.intent || "Inspect this section's notes, phrases, clips and changing controls."}</p></div><Button variant="outline" size="sm" onClick={() => { setDetailStart(null); onSelectSection(null) }}><Focus className="size-4" /> Whole piece</Button></div>
        <div className="score-window-controls"><span>Inspecting bars {windowStartBar + 1}–{windowEndBar} of {section.endBar}</span><div><Button variant="outline" size="sm" aria-label="Previous bars" disabled={windowStartBar <= section.startBar} onClick={() => setDetailStart(Math.max(section.startBar, windowStartBar - 8))}><ArrowLeft className="size-4" /></Button><Button variant="outline" size="sm" aria-label="Next bars" disabled={windowEndBar >= section.endBar} onClick={() => setDetailStart(windowEndBar)}><ArrowRight className="size-4" /></Button></div></div>
        <div className="score-detail-lanes">{document.parts.map((part) => { const material = materializedSectionNotes(document, part.id, windowStart, windowEnd, 120); const clips = sectionClips(document, part.id, windowStart, windowEnd); if (!material.total && !clips.length && !part.automation.some((curve) => curve.points.some((point) => point.tick >= windowStart && point.tick < windowEnd))) return null; const difference = sectionChanges?.parts.find((item) => item.partId === part.id); const addedKeys = new Set(difference?.addedNotes.map((note) => note.key)); const modifiedKeys = new Set(difference?.modifiedNotes.map((pair) => pair.after.key)); const ghosts = [...(difference?.removedNotes ?? []), ...(difference?.modifiedNotes.map((pair) => pair.before) ?? [])].filter((note) => note.startTick < windowEnd && note.startTick + note.durationTicks > windowStart).slice(0, 120); const pitches = [...material.notes, ...ghosts].map((note) => note.pitch); const low = Math.min(...pitches), high = Math.max(...pitches); return <div className="score-detail-lane" key={part.id}><button type="button" onClick={() => onInspectPart(part.id)}><small>{roleNames[part.role] ?? part.role}</small><strong>{part.name}</strong></button><svg viewBox="0 0 1000 56" preserveAspectRatio="none" role="img" aria-label={`${part.name}: ${material.total} notes, ${clips.length} clips in bars ${windowStartBar + 1}–${windowEndBar}${difference ? `; ${difference.addedNotes.length} added, ${difference.removedNotes.length} removed, ${difference.modifiedNotes.length} modified notes` : ""}`}>
          {Array.from({ length: windowEndBar - windowStartBar + 1 }, (_, index) => <line key={index} x1={index / (windowEndBar - windowStartBar) * 1000} x2={index / (windowEndBar - windowStartBar) * 1000} y1="0" y2="56" className="score-bar-line" />)}
          {clips.map((clip) => <rect key={clip.key} x={Math.max(0, (clip.startTick - windowStart) / (windowEnd - windowStart) * 1000)} y="36" width={Math.max(2, Math.min(1000, (clip.startTick + clip.durationTicks - windowStart) / (windowEnd - windowStart) * 1000) - Math.max(0, (clip.startTick - windowStart) / (windowEnd - windowStart) * 1000))} height="15" rx="3" className="score-detail-clip"><title>{clip.label} · source {clip.sourceStartSeconds.toFixed(2)}–{(clip.sourceStartSeconds + clip.sourceDurationSeconds).toFixed(2)} seconds · timeline bars {barLabel(clip.startTick, width)}–{barLabel(clip.startTick + clip.durationTicks, width)} · {clip.playbackMode ?? "once"}</title></rect>)}
          {ghosts.map((note) => <rect key={`ghost:${note.key}`} x={Math.max(0, (note.startTick - windowStart) / (windowEnd - windowStart) * 1000)} y={29 - (note.pitch - low) / Math.max(1, high - low) * 24} width={Math.max(2, Math.min(1000, (note.startTick + note.durationTicks - windowStart) / (windowEnd - windowStart) * 1000) - Math.max(0, (note.startTick - windowStart) / (windowEnd - windowStart) * 1000))} height="5" rx="2" className="score-note-removed"><title>{modifiedKeys.has(note.key) ? "Previous shape of modified note" : "Removed note"}: {pitchName(note.pitch)} at bar {barLabel(note.startTick, width)}</title></rect>)}
          {material.notes.map((note) => <rect key={note.key} x={Math.max(0, (note.startTick - windowStart) / (windowEnd - windowStart) * 1000)} y={pitches.length ? 29 - (note.pitch - low) / Math.max(1, high - low) * 24 : 20} width={Math.max(2, Math.min(1000, (note.startTick + note.durationTicks - windowStart) / (windowEnd - windowStart) * 1000) - Math.max(0, (note.startTick - windowStart) / (windowEnd - windowStart) * 1000))} height="5" rx="2" className={`score-detail-note role-${part.role} ${addedKeys.has(note.key) ? "score-note-added" : ""} ${modifiedKeys.has(note.key) ? "score-note-modified" : ""} ${highlightFamily && note.familyId !== highlightFamily ? "is-muted" : ""}`}><title>{addedKeys.has(note.key) ? "Added" : modifiedKeys.has(note.key) ? "Modified" : "Retained"} {pitchName(note.pitch)} · bar {barLabel(note.startTick, width)} · {note.durationTicks / 960} beats · velocity {Math.round(note.velocity * 100)}%{note.motifId ? ` · ${document.motifs.find((item) => item.id === note.motifId)?.name}` : ""}</title></rect>)}
        </svg><span className="score-detail-count">{material.total}{material.truncated ? "+" : ""} notes{clips.length ? ` · ${clips.length} clips` : ""}</span></div> })}</div>
        {selectedPart ? <div className="score-inspector" aria-label={`${selectedPart.name} musical facts`}><div className="score-inspector-heading"><Layers3 className="size-4" /><strong>{selectedPart.name}</strong><span>{roleNames[selectedPart.role] ?? selectedPart.role} · {selectedPart.device.type}</span></div><p>Level {Math.round(selectedPart.gain * 100)}% · balance {selectedPart.pan} · {selectedPart.groupId ? `routed through ${document.groups?.find((group) => group.id === selectedPart.groupId)?.name ?? selectedPart.groupId}` : "main output"}{selectedPart.sends?.length ? ` · ${selectedPart.sends.length} shared send(s)` : ""}</p><div className="score-inspector-grid"><div><b>Notes & phrases</b><ul>{materializedSectionNotes(document, selectedPart.id, section.startBar * width, section.endBar * width, 12).notes.map((note) => <li key={note.key}>{pitchName(note.pitch)} · bar {barLabel(note.startTick, width)} · {Number((note.durationTicks / 960).toFixed(2))} beats · velocity {Math.round(note.velocity * 100)}%{note.motifId ? ` · ${document.motifs.find((item) => item.id === note.motifId)?.name ?? "phrase"}` : ""}</li>)}</ul></div><div><b>Clips & controls</b><ul>{sectionClips(document, selectedPart.id, section.startBar * width, section.endBar * width).slice(0, 12).map((clip) => <li key={clip.key}>{clip.label} · bar {barLabel(clip.startTick, width)} · source {clip.sourceStartSeconds.toFixed(2)}–{(clip.sourceStartSeconds + clip.sourceDurationSeconds).toFixed(2)} s · {clip.playbackMode ?? "once"}{clip.playbackRate ? ` · ${clip.playbackRate}×` : ""}{clip.stretchMode ? ` · ${clip.stretchMode}` : ""}</li>)}{selectedPart.automation.map((curve) => <li key={curve.id}>{curve.target} · {curve.points.length} points · {curve.points.map((point) => `${barLabel(point.tick, width)}: ${point.value} (${point.interpolation ?? "step"})`).join("; ")}</li>)}{selectedPart.effects.map((effect) => <li key={effect.id}>{effect.type} · {Object.entries(effect.parameters).map(([key, value]) => `${key} ${value}`).join(", ")}</li>)}</ul></div></div><p className="score-inspector-note">Values are stored control values, not measured sound. The first 12 note and clip facts are shown here; use the timeline to inspect the selected bars.</p></div> : <p className="score-inspector-hint">Choose a part label to inspect exact note timing, phrase lineage, clip source intervals, controls and routing.</p>}
      </div> : null}
    </div>
  </MotionConfig>
}, (before, after) => before.identity === after.identity && before.selectedSectionId === after.selectedSectionId && before.selectedPartId === after.selectedPartId && before.comparisonBefore === after.comparisonBefore && before.draft === after.draft && before.animateConfirmed === after.animateConfirmed)
