import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createProject, decodeWav, devOwnerId, getPool, insertAsset, storeImmutableAudio, closePool } from "@pocket/core";

const ownerId = await devOwnerId();
const existing = await getPool().query<{ id: string }>("SELECT id FROM project WHERE owner_id=$1 AND title='Sunroom demo' AND deleted_at IS NULL LIMIT 1", [ownerId]);
const project = existing.rows[0] ? { id: existing.rows[0].id } : await createProject(ownerId, "Sunroom demo");
const fixturePath = resolve(process.cwd(), ".local", "fixtures", "owned-percussion.wav");
const bytes = await readFile(fixturePath);
const decoded = decodeWav(bytes);
const stored = await storeImmutableAudio(ownerId, project.id, bytes);
const assetId = await insertAsset({ ownerId, projectId: project.id, name: "owned-percussion.wav", hash: stored.hash, path: stored.path, durationSeconds: decoded.durationSeconds, sampleRate: decoded.sampleRate, channels: decoded.channels.length, provenance: "Generated by scripts/generate-fixtures.ts; CC0-equivalent project-owned fixture" });
process.stdout.write(`${JSON.stringify({ projectId: project.id, assetId })}\n`);
await closePool();
